### ISSUE TITLE
Docker-compose for easy development environment?

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-plugin-creativecommons#154]
## Problem

There are several steps required to begin developing this extension, such as

1. set up WordPress, a web server, and database locally
2. configure phpcs for WordPress coding standards
3. configure code standards in IDE

Each of these steps can prove to be problematic.

## Description

Adding a Docker compose file can help make some of the above steps easier. For example, a basic Docker-compose file can create a WordPress/Apache/MariaDB development environment in one command. The WordPress Docker container can automatically install the WordPress coding standards plugin via composer. 

Developers would want a choice of IDE. However, it is possible to configure VS Code to [develop within a Docker container](https://code.visualstudio.com/docs/remote/containers). For extra simplicity, we can serve a [VS Code Code Server](https://github.com/cdr/code-server) instance from within a Docker container pre-configured with PHP-related extensions.

This issue proposes to create a `docker-compose.yml` and possibly an extended WordPress Dockerfile within the `dev` folder.

## Alternatives

I've tried XAMPP locally. It brought back memories and is a good tool. However, it was somewhat quirky and posed issues with permissions, configuration, and debugging.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by brylie** [comment]
For reference, here is the `docker-compose.yml` I used to start developing `wp-plugin-creativecommons`.

```
# /wordpress-docker/docker-compose.yml
---
version: '3.3'
services:
    db:
        container_name: 'local-wordpress-db'
        image: 'mysql:5.7'
        volumes:
          - './data/mysql:/var/lib/mysql'
        ports:
          - 18766:3306
        environment:
          MYSQL_ROOT_PASSWORD: test1234
          MYSQL_DATABASE: wordpress_db
          MYSQL_USER: wordpress_user
          MYSQL_PASSWORD: test1234
    wordpress:
        container_name: 'local-wordpress'
        depends_on:
            - db
        image: 'wordpress:latest'
        ports:
            - '80:80'
        environment:
            WORDPRESS_DB_HOST: 'db:3306'
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: test1234
            WORDPRESS_DB_NAME: wordpress_db
        volumes:
            - "./wordpress:/var/www/html"
            - "./plugins:/var/www/html/wp-content/plugins"

```
